version: "3"

services:
  db:
    container_name: db
    restart: always
    image: postgres
    environment:
      POSTGRES_DB: pizzajs
      POSTGRES_USER: username
      POSTGRES_PASSWORD: pizza
    ports:
      - "5432:5432"

  pizzajs:
    container_name: pizzajs
    build: .
    depends_on:
      - db
    command: bash -c "yarn && yarn start && yarn sequelize db:migrate"
    ports:
      - "3333:3333"
    volumes:
      - .:/code